name: Flatpak build
on:
  push:
    branches: [feature/flatpak-manifest]
  pull_request:
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: devpod.flatpak
        manifest-path: desktop/src-tauri/flatpak.yml
        cache-key: flatpak-builder-${{ github.sha }}